### PR TITLE
Update CoderData.json

### PR DESCRIPTION
**Pull request by Rohit-110**
Issue: #1 
Added my Credentials
image

### CODE REVIEW

**Comment by Fremdder** [comment]
follow PR template from [PR_TEMPLATE.md](https://github.com/opencodeiiita/Code-Digger-2023/blob/main/PR_TEMPLATE.md)

**Comment by Rohit-110** [comment]
Merge Conflicts Resolved

**Comment by Fremdder** [comment]
you have to follow PR template to get points which is described in PR_TEMPLATE.md or you can see past pull request which are merged

**Comment by Rohit-110** [comment]
Done Thanks!

**Pull request merged**
